### ISSUE TITLE
OpenApi integration: Design First Approach

### ISSUE THREAD

**Issue by vyarmolovich** [agrestio/agrest#285]
It would be nice to have ability to generate LinkRest api implementation based on swagger definition automatically.
As a model classes should be used classes generated by Cayenne. 

- [x] #324 Create swager codegen to generate API rsources from .yaml definition.
- [x] #298 Update swagger codegen and templates to implement custom parameters processing
- [x] #335 Provide ability to generate POJO models if the existing ones are not used.
- [x] #336 Design-first approach. Create two modules `agrest-openapi-designfirst` and `agrest-openapi-designfirst-test`
- [x] #345 Design-first approach. Provide an application example based on the 'bookstore'

The main workflow:
1. Create swagger definition in yaml format manually or using the [Swagger Editor](http://editor.swagger.io/):
```
openapi: 3.0.0
servers:
  - url: 'http://127.0.0.1/v1'
info:
  title: LinkRest based Api
  description: An API for interacting with the backend server
  version: v1


tags:
  - name: Domain
    description: |
      This resourse allows you to retrive and update Domains information.

paths:
 /domains:
    get:
      summary: Get all Domains
      operationId: getAll
      tags:
        - Domain
      parameters: 
        - $ref: '../resources/protocol.yaml#/components/queryParams/Limit'
      responses:
        '200':
          description: Success response. 
          schema: 
            type: array
            items:
              $ref: '#/components/schemas/Domain’
        default:
          description: Unexpected error

  /domains/{id}:
    get:
      description: Returns a Domain
      operationId: getOne
      tags: 
        - Domain
      parameters: 
        - name: id
          in: path
          description: ID of E1 to fetch
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success responce
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
          description: Unexpected error

components:
  schemas:
    Domain:
      type: object
      properties:
       id:
         type: string
         description: Unique ID of Domain
         example: 1
       name:
         type: string
         description: Domain name
         example: My Site #1
       vhost:
	 type: string
   	 description: 
	 example: mysite1
```
2. Add swagger plugin to maven pom.xml and run api generation
2.1. Specify custom `LinkRestServerCodegen` in `<language>` element
2.2. Specify path to Cayenne models in `<modelPackage>` element
2.3. Run api generation by `mvn clean compile` command
```
    <build>
        <plugins>
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>${swagger-codegen-maven-plugin-version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${swagger-spec}</inputSpec>
                            <language>io.swagger.codegen.languages.LinkRestServerCodegen</language>
                            <output>${project.basedir}</output>
                            <apiPackage>${base-package}.swagger.api.v${schema-version}.service</apiPackage>
                            <modelPackage>${base-package}.it.fixture.cayenne</modelPackage>
                            <invokerPackage>${base-package}</invokerPackage>
                            <generateModels>false</generateModels>
                            <configOptions>
                                <generateForTesting>true</generateForTesting>
                                <generateSpringApplication>false</generateSpringApplication>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>com.nhl.link.rest.swagger</groupId>
                        <artifactId>link-rest-swagger-desingfirst</artifactId>
                        <version>${project.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```
3. Get resulted api implementation based on LinkRest
```
@Path("/")
public class DomainApiServiceImpl implements DomainApi {

    @Context
    private Configuration config;

    @GET
    @Path("/v1/domains")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    public DataResponse<io.bootique.linkrest.demo.cayenne.Domain> getAll( @Context UriInfo uriInfo, @QueryParam Limit limit) {
        // Explicit query parameter
        LrRequest lrRequest = LrRequest.builder().limit(limit).build();

        return LinkRest.select(io.bootique.linkrest.demo.cayenne.Domain.class, config)
                .attribute(“name”)
                .attribute("id")
		.attribute(“vhost”)
            )
            .uri(uriInfo)
            .request(lrRequest) // overrides parameters from uriInfo
            .get();
    }

    @GET
    @Path("/v1/domains/{id}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    public DataResponse<io.bootique.linkrest.demo.cayenne.Domain> getOne(@PathParam("id") Long id,  @Context UriInfo uriInfo) {

        return LinkRest.select(io.bootique.linkrest.demo.cayenne.Domain.class, config)
                .attribute(“name”)
                .attribute("id")
		.attribute(“vhost”)
            )
            .byId(id)
            .uri(uriInfo).get();
    }
}
```
