### ISSUE TITLE
JPA Integration

### ISSUE THREAD

**Issue by vyarmolovich** [agrestio/agrest#359]
- [ ] #364 Introduce an expression engine - `AgExp`
- [ ] #365 Refactor `ExpressionPostProcessor` to use Agrest Expression
- [ ] #366 Refactoring stages 
- [ ] #367 Create converters for `AgExpression`, `AST*` and `Ordering`.
- [ ] #368 move Cayenne runtime to separate module
- [ ] #382 Delegate Expression processing to Cayenne\JPA side
